### ISSUE TITLE
Error: unprocessable entity

### ISSUE THREAD

**Issue by grssnbchr** [public-transport/db-vendo-client#1]
The int.bahn.de server seems to respond with an unprocessable entity when using `journeys`.
Just running /p/db/example.js with 

```
 let data = await client.journeys(berlinJungfernheide, münchenHbf, {
        results: 1,
        tickets: true,
 })
```

errors out at

```
		const err = new Error(res.statusText);
		            ^

Error: Unprocessable Entity
    at Object.request (file:///home/tgrossen/Projekte/Technical/db-vendo-client/lib/request.js:142:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.journeys (file:///home/tgrossen/Projekte/Technical/db-vendo-client/index.js:213:25)
    at async file:///home/tgrossen/Projekte/Technical/db-vendo-client/p/db/example.js:38:13
```

**Comment by traines-source** [comment]
Sorry, I miscommitted something yesterday :( Should be fixed now. Thanks for reporting!

**Comment by grssnbchr** [comment]
No worries - can confirm it works now.
